name: Trigger auto deployment for presentech

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/backend/**'
    - '.github/workflows/presentech-AutoDeployTrigger-d37a73f1-5255-41d8-821b-8c9e25b5aa69.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRESENTECH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRESENTECH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRESENTECH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/backend
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.PRESENTECH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRESENTECH_REGISTRY_PASSWORD }}
          containerAppName: presentech
          resourceGroup: Presentech
          imageToBuild: sazapatac/presentech:${{ github.sha }}



